# Notification Settings
notification.email.smtp.auth=true
notification.email.smtp.username=${REVEILA_NOTIFY_SMTP_USERNAME}
notification.email.smtp.password=${REVEILA_NOTIFY_SMTP_PASSWORD}
notification.email.smtp.port=587
notification.email.smtp.server=smtp.gmail.com
