# The configuration file for the Reveila System
# This file is used to configure the various aspects of the system.
# The keys in this file are case-sensitive.
# Use the ${key} syntax to reference other properties.
# Use the ${env.key} syntax to reference environment variables.
# Use the ${system.key} syntax to reference system properties.

# The name of the system
system.name=Reveila

# The version of the system
system.version=1.0.0

# The mode in which the system is running (e.g., prod, dev, test)
system.mode=demo

# The character encoding used for text processing
text.character.encoding=UTF-8

# The encryption and decryption key
cryptographer.secretkey=${REVEILA_ENCRYPT_KEY}

# The directory where system logs are stored
# log.dir=logs

# The logging level (e.g., ALL, FINEST, FINER, FINE, CONFIG, INFO, WARNING, SEVERE, OFF)
logging.level.root=INFO

# The maximum size of each log file in bytes
logging.file.size=20480

# The number of log files to keep in rotation
logging.file.count=1

# Whether to enable logging to the console
logging.console.enabled=true

# The timeout for component startup in seconds
component.start.timeout=30

# The database host
REVEILA_DB_HOST=localhost

# The database name
REVEILA_DB_NAME=reveila_db

# The database password
REVEILA_DB_PASSWORD=${REVEILA_DB_PASSWORD}

# The database username
REVEILA_DB_USER=${REVEILA_DB_USERNAME}

# The AI worker to use for general tasks
ai.governance.worker=openai

# The AI guardrail to use for security and policy enforcement
ai.governance.guardrail=gemini

# The directory where local plugins are stored
# plugin.local.dir=plugins/active

# The path to the plugin repository
# plugin.repository.path=plugins/repository

# The web root directory
# web-root=web

# The static resources locations
# spring.web.resources.static-locations=file:${web-root}/,classpath:/static/

# The standalone mode (true/false)
system.standalone=true

# The platform on which the system is running (e.g., spring, android)
# platform=spring
platform=android
