/*
 * This source file was generated by the Gradle 'init' task
 */
package reveila.adapters;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestImpl {
    @Test void writeYourTestHere() {
        //Library classUnderTest = new Library();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
