#Updated via Dashboard Settings
#Sat Mar 14 20:11:43 CDT 2026
REVEILA_DB_HOST=localhost
REVEILA_DB_NAME=reveila_db
REVEILA_DB_PASSWORD=your_secure_password
REVEILA_DB_USER=admin
db.create.schema=true
