notification.alert.email=ciso-alerts@reveila.com
notification.alert.threshold=0.80
notification.email.smtp.server=smtp.gmail.com
notification.email.smtp.port=587
notification.email.smtp.auth=true
notification.email.smtp.username=reveila.dev@gmail.com
notification.email.smtp.password=Ilove2dev!
