debug=true
track=true
download.base.url=https://reveila.com/downloads
db.create.schema=true
REVEILA_DB_HOST=localhost
REVEILA_DB_NAME=reveila_db
REVEILA_DB_PASSWORD=${REVEILA_DB_PASSWORD}
REVEILA_DB_USER=${REVEILA_DB_USERNAME}
ai.governance.llm=On-Device Model
ai.worker.llm=On-Device Model
ai.optimization.priority=cost
ai.optimization.history=10MB
ai.show.reasoning=false
auth.session.timeout=30
component.start.timeout=5
logging.console.enabled=true
logging.file.count=2
logging.file.size=20480
logging.level.com.reveila=DEBUG
logging.level.root=INFO
management.endpoint.env.show-values=always
management.endpoints.web.exposure.include=health,info,metrics,env
notification.alert.email=ciso-alerts@reveila.com
notification.alert.threshold=0.80
notification.email.smtp.server=smtp.gmail.com
notification.email.smtp.username=${REVEILA_NOTIFY_SMTP_USERNAME}
notification.email.smtp.password=${REVEILA_NOTIFY_SMTP_PASSWORD}
notification.email.smtp.port=587
notification.email.smtp.auth=true
plugin.local.dir=${system.home}/plugins
plugin.repository.path=${system.home}/downloads/plugins
spring.web.resources.static-locations=file\:${web-root}/,classpath\:/static/
system.mode=demo
system.name=Reveila
system.standalone=true
system.version=1.0.0
tenant-id=tenant-0
web-root=${system.home}/web
# platform=spring
platform=android